import {ConfigFile} from '../../generator/types';
export const config: ConfigFile = {
  rootOptions: {
    configFile: 'src/20260622_AaveV3InkWhitelabel_InkMarketIsolationUpdate/config.ts',
    force: true,
    pools: ['AaveV3InkWhitelabel'],
    title: 'Ink Market Isolation Update',
    shortName: 'InkMarketIsolationUpdate',
    date: '20260622',
    author: 'EvanInkFnd',
  },
  poolOptions: {
    AaveV3InkWhitelabel: {
      configs: {
        RATE_UPDATE_V3: [
          {
            asset: 'USDC',
            params: {
              optimalUtilizationRate: '90',
              baseVariableBorrowRate: '6.5',
              variableRateSlope1: '0',
              variableRateSlope2: '0',
            },
          },
        ],
        COLLATERALS_UPDATE: [
          {
            asset: 'WETH',
            ltv: '0',
            liqThreshold: '',
            liqBonus: '',
            debtCeiling: '',
            liqProtocolFee: '',
          },
          {
            asset: 'kBTC',
            ltv: '85',
            liqThreshold: '87',
            liqBonus: '5',
            debtCeiling: '',
            liqProtocolFee: '',
          },
          {
            asset: 'USDT',
            ltv: '0',
            liqThreshold: '',
            liqBonus: '',
            debtCeiling: '',
            liqProtocolFee: '',
          },
          {
            asset: 'weETH',
            ltv: '0',
            liqThreshold: '',
            liqBonus: '',
            debtCeiling: '',
            liqProtocolFee: '',
          },
          {
            asset: 'ezETH',
            ltv: '0',
            liqThreshold: '',
            liqBonus: '',
            debtCeiling: '',
            liqProtocolFee: '',
          },
          {
            asset: 'SolvBTC',
            ltv: '0',
            liqThreshold: '',
            liqBonus: '',
            debtCeiling: '',
            liqProtocolFee: '',
          },
        ],
        BORROWS_UPDATE: [
          {
            asset: 'WETH',
            enabledToBorrow: 'DISABLED',
            flashloanable: 'KEEP_CURRENT',
            borrowableInIsolation: 'KEEP_CURRENT',
            withSiloedBorrowing: 'KEEP_CURRENT',
            reserveFactor: '',
          },
          {
            asset: 'kBTC',
            enabledToBorrow: 'DISABLED',
            flashloanable: 'KEEP_CURRENT',
            borrowableInIsolation: 'KEEP_CURRENT',
            withSiloedBorrowing: 'KEEP_CURRENT',
            reserveFactor: '',
          },
          {
            asset: 'USDT',
            enabledToBorrow: 'DISABLED',
            flashloanable: 'KEEP_CURRENT',
            borrowableInIsolation: 'KEEP_CURRENT',
            withSiloedBorrowing: 'KEEP_CURRENT',
            reserveFactor: '',
          },
          {
            asset: 'USDG',
            enabledToBorrow: 'DISABLED',
            flashloanable: 'KEEP_CURRENT',
            borrowableInIsolation: 'KEEP_CURRENT',
            withSiloedBorrowing: 'KEEP_CURRENT',
            reserveFactor: '',
          },
          {
            asset: 'GHO',
            enabledToBorrow: 'DISABLED',
            flashloanable: 'KEEP_CURRENT',
            borrowableInIsolation: 'KEEP_CURRENT',
            withSiloedBorrowing: 'KEEP_CURRENT',
            reserveFactor: '',
          },
          {
            asset: 'USDe',
            enabledToBorrow: 'DISABLED',
            flashloanable: 'KEEP_CURRENT',
            borrowableInIsolation: 'KEEP_CURRENT',
            withSiloedBorrowing: 'KEEP_CURRENT',
            reserveFactor: '',
          },
        ],
        EMODES_ASSETS: [
          {
            asset: 'sUSDe',
            eModeCategory: '2',
            collateral: 'KEEP_CURRENT',
            borrowable: 'KEEP_CURRENT',
            ltvzero: 'ENABLED',
          },
          {
            asset: 'USDe',
            eModeCategory: '2',
            collateral: 'KEEP_CURRENT',
            borrowable: 'KEEP_CURRENT',
            ltvzero: 'ENABLED',
          },
          {
            asset: 'USDe',
            eModeCategory: '3',
            collateral: 'KEEP_CURRENT',
            borrowable: 'KEEP_CURRENT',
            ltvzero: 'ENABLED',
          },
        ],
        EMODES_CREATION: [
          {
            ltv: '90',
            liqThreshold: '92',
            liqBonus: '4',
            label: 'sUSDe_USDe__USDT0_USDG',
            collateralAssets: ['sUSDe', 'USDe'],
            borrowableAssets: ['USDT', 'USDG'],
          },
        ],
      },
      cache: {blockNumber: 48658329},
    },
  },
};
